apiVersion: constraints.gatekeeper.sh/v1beta1
kind: TFGCPIAMAllowedBindingsConstraintV3
metadata:
  name: deny_cicdsa
  annotations:
    description: Prevent additional role grants to cicd service accounts
    bundles.validator.forsetisecurity.org/scorecard-v1: security
    bundles.validator.forsetisecurity.org/healthcare-baseline-v1: security
spec:
  severity: high
  match:
    ancestries: # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
      - "organizations/**"
    exclude: [] # optional, default is no exclusions
  parameters:
    mode: denylist
    role: "roles/*"
    members:
      # - "allUsers"
      # - "allAuthenticatedUsers"
      # Add Service accounts used by the CICD Pipeline
      - cloubuild-dev-sa@w-app-pipeline.iam.gserviceaccount.com
      - cloubuild-prod-sa@w-app-pipeline.iam.gserviceaccount.com
